
arduino-builder -dump-prefs -logger=machine -hardware /usr/share/arduino/hardware -hardware /home/pablo/Descargas/$documents/MATLAB/SupportPackages/R2018a/3P.instrset/arduinoide.instrset/idepkgs/packages -tools /usr/share/arduino/hardware/tools/avr -tools /home/pablo/Descargas/$documents/MATLAB/SupportPackages/R2018a/3P.instrset/arduinoide.instrset/idepkgs/packages -libraries /home/pablo/Documentos/Arduino/parpadeo/parpadeo/libraries -fqbn=arduino:avr:uno -ide-version=10819 -build-path /tmp/MW_ArduinoHWSetup/MW_ArduinoBuild -warnings=none -build-cache /tmp/arduino_cache_359183 -prefs=build.warn_data_percentage=75 -verbose /home/pablo/Documentos/Arduino/parpadeo/parpadeo/sketch_oct06a/sketch_oct06a.ino
arduino-builder -compile -logger=machine -hardware /usr/share/arduino/hardware -hardware /home/pablo/Descargas/$documents/MATLAB/SupportPackages/R2018a/3P.instrset/arduinoide.instrset/idepkgs/packages -tools /usr/share/arduino/hardware/tools/avr -tools /home/pablo/Descargas/$documents/MATLAB/SupportPackages/R2018a/3P.instrset/arduinoide.instrset/idepkgs/packages -libraries /home/pablo/Documentos/Arduino/parpadeo/parpadeo/libraries -fqbn=arduino:avr:uno -ide-version=10819 -build-path /tmp/MW_ArduinoHWSetup/MW_ArduinoBuild -warnings=none -build-cache /tmp/arduino_cache_359183 -prefs=build.warn_data_percentage=75 -verbose /home/pablo/Documentos/Arduino/parpadeo/parpadeo/sketch_oct06a/sketch_oct06a.ino
Using board 'uno' from platform in folder: /usr/share/arduino/hardware/arduino/avr
Using core 'arduino' from platform in folder: /usr/share/arduino/hardware/arduino/avr

Detecting libraries used...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch/sketch_oct06a.ino.cpp" -o "/dev/null"

Generating function prototypes...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch/sketch_oct06a.ino.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/preproc/ctags_target_for_gcc_minus_e.cpp"
"/usr/bin/arduino-ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/preproc/ctags_target_for_gcc_minus_e.cpp"

Compilando programa...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch/sketch_oct06a.ino.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch/sketch_oct06a.ino.cpp.o"

Compiling libraries...
Compiling core...
"/usr/bin/avr-gcc" -c -g -x assembler-with-cpp -flto -MMD -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.S" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_pulse.S.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WInterrupts.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/hooks.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_analog.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_digital.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_pulse.c.o"
"/usr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_shift.c.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/CDC.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial0.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial1.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial2.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial3.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/IPAddress.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/PluggableUSB.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/PluggableUSB.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Print.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Stream.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Tone.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/USBCore.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WMath.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WString.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/abi.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/main.cpp.o"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp" -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/new.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_pulse.S.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WInterrupts.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/hooks.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_analog.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_digital.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_pulse.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/wiring_shift.c.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/CDC.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial0.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial1.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial2.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/HardwareSerial3.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/IPAddress.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/PluggableUSB.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Print.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Stream.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/Tone.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/USBCore.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WMath.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/WString.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/abi.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/main.cpp.o"
"/usr/bin/avr-gcc-ar" rcs  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/new.cpp.o"
Archiving built core (caching) in: /tmp/arduino_cache_359183/core/core_arduino_avr_uno_1621df717313d057c92202babd71649a.a
Linking everything together...
"/usr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p   -o "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch_oct06a.ino.elf" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch/sketch_oct06a.ino.cpp.o"  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/core/core.a" "-L/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild" -lm
"/usr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch_oct06a.ino.elf" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch_oct06a.ino.eep"
"/usr/bin/avr-objcopy" -O ihex -R .eeprom  "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch_oct06a.ino.elf" "/tmp/MW_ArduinoHWSetup/MW_ArduinoBuild/sketch_oct06a.ino.hex"
El Sketch usa 930 bytes (2%) del espacio de almacenamiento de programa. El máximo es 32256 bytes.
Las variables Globales usan 9 bytes (0%) de la memoria dinámica, dejando 2039 bytes para las variables locales. El máximo es 2048 bytes.
